server:
 port: 8888

spring:
 application:
  name: config-bus-server
 cloud:
  config:
   server:
    git:
     # 配置仓库的git地址
     uri: https://github.com/sleepy-zeo/spring-cloud-configs
     # 配置仓库的路径
     search-paths: config-files
     # 配置仓库的用户名(私有仓库必需)
     username:
     # 配置仓库的密码(私有仓库必需)
     password:
   # 配置仓库的分支
   label: main
 # 1. 添加在配置中心
 # 2. 添加在所有需要接收消息的客户端中
 rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

# 添加在配置中心
management:
 server:
  port: 8899
 endpoints:
  web:
   exposure:
    #
    # bus-refresh
    # 刷新所有 curl -X POST http://localhost:8899/actuator/bus-refresh
    # 刷新某个 curl -X POST http://localhost:8899/actuator/bus-refresh/{destination}
    # destination = 微服务名:端口号
    #
    # bus-env
    # ADD/UPDATE某个键值对 curl -X POST -H "Content-Type: application/json" -d '{"name":"info","value":"steven"}' http://localhost:8899/actuator/bus-env
    #
    # /actuator下一共有20个，目前只暴露了两个
    #
    include: bus-refresh, bus-env
