server:
 port: 8888

spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
     # ?????git??
     uri: https://github.com/sleepy-zeo/scc
     # ???????
     search-paths: sconfigs
     # ????????(??????)
     username:
     # ???????(??????)
     password:
   # ???????
   label: master

