server:
 port: 19540

spring:
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

management:
 server:
  port: 8899
 endpoints:
  web:
   exposure:
    # actuator模块提供了数个endpoint，bus模块提供了两个endpoint
    # 这里我们只暴露bus模块提供的两个endpoint: bus-refresh bus-env
    include: bus-refresh, bus-env
