server:
 port: 9098

spring:
 application:
  name: bus-config-client
 cloud:
  config:
   # 远端的文件会覆盖本地的application.yml中同名属性的值
   label: main
   profile: dev
   uri: http://localhost:8888/
   name: bus-config-client
  # bus
  bus:
   trace:
    enabled: true
 rabbitmq:
  host: localhost
  port: 5555
  username:
  password:

