server:
 port: 3800
 servlet:
  context-path: /provider

spring:
 application:
  name: eureka-client-provider

eureka:
 instance:
  instance-id: ${spring.application.name}:localhost:${server.port}
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:1124/server/eureka/


